version: '3.8'

services:
  
  postgres:
    image: postgres:15
    container_name: do-bem-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dobem
    ports:
      - 5432:5432
    hostname: postgres-db
